### ISSUE TITLE
[Question] Beacondb with Firefox?

### ISSUE THREAD

**Issue by Mikaela** [beacondb/beacondb#8]
Is it possible to use beacondb with Firefox? I am on Firefox Developer Edition 128.0b8 (64-bittinen) on Fedora 40 and trying with openstreetmap.org and hsl.fi I either get no errors or I get a prompt saying geolocation failed.

I have been trying to set `geo.provider.network.url` to `https://beacondb.net/v1/geolocate` and wondered if Firefox expects there to be a question mark so I have tried `https://beacondb.net/v1/geolocate?` and `https://beacondb.net/v1/geolocate?key=null` https://beacondb.net/v1/geolocate?key=test` and even `https://beacondb.net/v1/geolocate?key=%GOOGLE_LOCATION_SERVICE_API_KEY%` with no luck. I also tried to set `geo.provider.use_geoclue` to false and restart Firefox every time I adjusted `about:config`, but no luck.

It might also be something wrong with my system configuration, but I thought I would ask just in case.

**Comment by joelkoen** [comment]
Grepping through my server logs, some other users have run into this issue as well so it is definitely not on your side.

Thank you for letting me know, I'll take a look now.

**Comment by joelkoen** [comment]
Looks like Firefox is sending the MAC addresses using a different format than I expected, using `aa-aa-aa-aa-aa-aa` instead of `aa:aa:aa:aa:aa:aa`. This should be fixed by tomorrow :)

**Comment by EchedelleLR** [comment]
@joelkoen both formats should be valid I think.

**Comment by joelkoen** [comment]
Yes, turns out the library I'm using was correctly parsing both and I just forgot I had disabled wifi location on the server as I was still working on it.

I've deployed a new algorithm and it's working for me from Firefox once I've set `geo.provider.network.url` to `https://beacondb.net/v1/geolocate`. Is this working for you now?

**Comment by Mikaela** [comment]
Sadly not, I am still getting variants of `Geolocation error: Unknown error acquiring position.`.

**Comment by Mikaela** [comment]
Judging by https://stackoverflow.com/a/3041637 this is an user error since if Firefox only sends currently connected WiFi on Linux, it's sending _nomap which isn't supposed to resolve. And it does work on Android.

**Comment by EchedelleLR** [comment]
I made some tests to the api before this change you made @joelkoen 

Sometimes it returned 400 (single request without body) and other times 404 (content request with body)

I am unsure if there is something wrong at the server configuration but 404 is not something expected to be thrown.

**Comment by EchedelleLR** [comment]
Oh, so the change fixed it.

Anyways @joelkoen could you reply why 404 on wrong user input? That is still something not normal.

**Comment by Mikaela** [comment]
The API documentation hints that 404 is normal.

- https://ichnaea.readthedocs.io/en/latest/api/geolocate.html#deviations-from-gls-api
- https://ichnaea.readthedocs.io/en/latest/api/geolocate.html#response

**Comment by EchedelleLR** [comment]
Should not be at least with a response body?

Because the 404 alone itself tells the endpoint does not exist or similar.

But is true I did not expect to be something also documented so I never checked the status codes in the documentation ;-;

Ouch. I apologize for losing your time there and thank you @Mikaela

**Comment by joelkoen** [comment]
> Sometimes it returned 400 (single request without body) and other times 404 (content request with body)

If you're intercepting the requests from Firefox, my server seems to be returning 400 when the client attempts to request to close the connection. I'm not too sure why these requests are even hitting my code as I think nginx should be closing the request.

> Should not be at least with a response body?
> Because the 404 alone itself tells the endpoint does not exist or similar.

Yes, good catch. I've just added a proper error message - 1d197f4

**Comment by joelkoen** [comment]
> Judging by https://stackoverflow.com/a/3041637 this is an user error since if Firefox only sends currently connected WiFi on Linux, it's sending _nomap which isn't supposed to resolve. And it does work on Android.

Yes, I've noticed that Firefox seems to only send one WiFI network, which my server does not accept for privacy reasons. On my system it does seem to send more sometimes, but it seems to be random...
